<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>FoundryWebUI-X.UnitTests</AssemblyName>
    <RootNamespace>FoundryWebUI.UnitTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" Version="1.45.29" />
    <PackageReference Include="Imposter" Version="0.1.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FoundryWebUI-X.TestInfrastructure\FoundryWebUI-X.TestInfrastructure.csproj" />
    <ProjectReference Include="..\..\FoundryWebUI-X.csproj" />
  </ItemGroup>

</Project>
